### ISSUE TITLE
Align images in markdown

### ISSUE THREAD

**Issue by fr0gs** [eugenekolo/cozy-youth-theme#2]
Hello! I love your theme and I just forked it.

I wonder if you could tell me how to align images in the same line using markdown the way you did in your **About Me** page.

Cheers.

**Comment by eugenekolo** [comment]
@fr0gs did you get it working? For things like that I hand-write the HTML in Ghost Blog backend.

**Comment by fr0gs** [comment]
Hello @eugenekolo , yes, I did. It was the first time I wrote markdown for something like that so I thought I could use html + markdown mixed, but at the end I just transformed the images into html as well and fit them inside the:

```
<div style="display:inline"> ... image ... </div>
```

**Comment by eugenekolo** [comment]
Cool. Yeah, after using Markdown long enough, I've realized it's pretty near useless for anything except simple documentation. End up having to resort to HTML anyway.
