### ISSUE TITLE
Add init to syntax highlighting

### ISSUE THREAD

**Issue by jthomp888999** [eugenekolo/cozy-youth-theme#3]
To default.hbs

<script>hljs.initHighlightingOnLoad();</script>

 got syntax highlighting working for me again.

**Comment by eugenekolo** [comment]
Hey @jthomp888999  can you let me know in what version of ghost syntax highlighting broke?

**Comment by jthomp888999** [comment]
I'm actually using 11.9 so I'm not sure if that is a problem for the new versions. I just went off highlight.js's documentation.

**Comment by eugenekolo** [comment]
@jthomp888999 Okay, cool. I'll take a look at reproducing this bug. I'm a bit unclear why it's not working, as the same line is executed in a jquery document.ready https://github.com/eugenekolo/cozy-youth-theme/blob/master/assets/js/index.js

**Comment by jthomp888999** [comment]
Oh wow yeah that is weird. I'm using the default setup from DigitalOcean just started and installed your theme. I'll re do everything and see if I'm still getting the error.
