### ISSUE TITLE
Remove Google+ from shared Post and replace

### ISSUE THREAD

**Issue by xchose** [eugenekolo/cozy-youth-theme#5]
Hello I would like to remove Google+ from shared Post and replace with something actuall. Lets say LinkedIn will be greate. Thank you
<img width="209" alt="Screen Shot 2020-03-30 at 7 59 28 PM" src="https://user-images.githubusercontent.com/464098/77945548-1bddd980-72c1-11ea-89bf-366e00c3c1a3.png">

**Comment by eugenekolo** [comment]
Hi @xchose, I changed it over to LinkedIn, you can give it a try and see if it works. Unfortunately, I do not have an environment to easily test the changes on at this time, and have moved on to other things.
